#ifndef NALI_VK_PIPELINEDYNAMICSTATECREATEINFO_H
#define NALI_VK_PIPELINEDYNAMICSTATECREATEINFO_H

void vk_setPipelineDynamicStateCreateInfo(VkDynamicState* vkdynamicstate_ptr, uint32_t vkdynamicstate_ptr_size, VkPipelineDynamicStateCreateFlags vkpipelinedynamicstatecreateflags, VkPipelineDynamicStateCreateInfo* vkpipelinedynamicstatecreateinfo_ptr);

#endif