#ifndef NALI_VK_PIPELINECOLORBLENDSTATECREATEINFO_H
#define NALI_VK_PIPELINECOLORBLENDSTATECREATEINFO_H

void vk_setPipelineColorBlendStateCreateInfo(VkPipelineColorBlendAttachmentState* vkpipelinecolorblendattachmentstate_ptr, VkPipelineColorBlendStateCreateFlags vkpipelinecolorblendstatecreateflags, VkPipelineColorBlendStateCreateInfo* vkpipelinecolorblendstatecreateinfo_ptr);

#endif