#ifndef NALI_VK_H
#define NALI_VK_H

#define NALI_VK_SGPU
#define NALI_VK_INFO_SC

#define NALI_VK_VERSION VK_API_VERSION_1_0//VK_API_VERSION_1_0 VK_API_VERSION_1_4

#define NALI_VK_COLOR_FORMAT_BYTE 4
#define NALI_VK_COLOR_FORMAT VK_FORMAT_R8G8B8A8_UNORM
#define NALI_VK_COLOR_SPACE VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
#define NALI_VK_DEPTH_FORMAT VK_FORMAT_D32_SFLOAT//VK_FORMAT_D16_UNORM

#define NALI_VK_SAMPLE_S VK_TRUE//VK_FALSE
#define NALI_VK_SAMPLE_C VK_SAMPLE_COUNT_8_BIT//VK_SAMPLE_COUNT_1_BIT
#define NALI_VK_SAMPLE_V 1.0F//0

#define NALI_VK_PRESENT VK_PRESENT_MODE_FIFO_KHR//VK_PRESENT_MODE_IMMEDIATE_KHR

#define NALI_VK_MAX_SAMPLER_ANISOTROPY 16.0F//0

extern uint32_t vk_device;
extern uint32_t vk_queue_g;
extern uint32_t vk_queue_ct;

extern uint8_t vk_non_coherent_atom_size;

void vk_set();
void vk_free();

#endif
