#ifndef _VK_DESCRIPTORSET_LAYOUT_H
#define _VK_DESCRIPTORSET_LAYOUT_H

void vkdslo_make(uint32_t device, VkDescriptorSetLayoutBinding *vkdescriptorsetlayoutbinding_p, uint32_t vkdescriptorsetlayoutbinding_size, VkDescriptorSetLayout *vkdescriptorsetlayout_p);

#endif