void vk_setPipelineVertexInputStateCreateInfo(VkPipelineVertexInputStateCreateFlags vkpipelinevertexinputstatecreateflags, VkPipelineVertexInputStateCreateInfo* vkpipelinevertexinputstatecreateinfo_ptr)
{
	vkpipelinevertexinputstatecreateinfo_ptr->sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
	vkpipelinevertexinputstatecreateinfo_ptr->vertexBindingDescriptionCount = 0;
	vkpipelinevertexinputstatecreateinfo_ptr->pVertexBindingDescriptions = VK_NULL_HANDLE;
	vkpipelinevertexinputstatecreateinfo_ptr->vertexAttributeDescriptionCount = 0;
	vkpipelinevertexinputstatecreateinfo_ptr->pVertexAttributeDescriptions = VK_NULL_HANDLE;
	vkpipelinevertexinputstatecreateinfo_ptr->flags = vkpipelinevertexinputstatecreateflags;
	vkpipelinevertexinputstatecreateinfo_ptr->pNext = VK_NULL_HANDLE;
}