void vk_setPipelineInputAssemblyStateCreateInfo(VkPipelineInputAssemblyStateCreateFlags vkpipelineinputassemblystatecreateflags, VkPipelineInputAssemblyStateCreateInfo* vkpipelineinputassemblystatecreateinfo_ptr)
{
	vkpipelineinputassemblystatecreateinfo_ptr->sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
	vkpipelineinputassemblystatecreateinfo_ptr->topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
	vkpipelineinputassemblystatecreateinfo_ptr->primitiveRestartEnable = VK_FALSE;
	vkpipelineinputassemblystatecreateinfo_ptr->flags = vkpipelineinputassemblystatecreateflags;
	vkpipelineinputassemblystatecreateinfo_ptr->pNext = VK_NULL_HANDLE;
}