#ifndef NALI_VK_DESCRIPTORSET_LAYOUT_H
#define NALI_VK_DESCRIPTORSET_LAYOUT_H

void vk_makeDescriptorSetLayout(uint32_t device, VkDescriptorSetLayoutBinding *vkdescriptorsetlayoutbinding_p, uint32_t vkdescriptorsetlayoutbinding_size, VkDescriptorSetLayout *vkdescriptorsetlayout_p);

#endif