#ifndef NALI_VK_PIPELINEINPUTASSEMBLYSTATECREATEINFO_H
#define NALI_VK_PIPELINEINPUTASSEMBLYSTATECREATEINFO_H

void vk_setPipelineInputAssemblyStateCreateInfo(VkPipelineInputAssemblyStateCreateFlags vkpipelineinputassemblystatecreateflags, VkPipelineInputAssemblyStateCreateInfo *vkpipelineinputassemblystatecreateinfo_p);

#endif