#ifndef NALI_VK_GRAPHICSPIPELINE_COLORBLENDSTATECREATEINFO_H
#define NALI_VK_GRAPHICSPIPELINE_COLORBLENDSTATECREATEINFO_H

void vk_setPipelineColorBlendStateCreateInfo(VkPipelineColorBlendAttachmentState *vkpipelinecolorblendattachmentstate_p, VkPipelineColorBlendStateCreateFlags vkpipelinecolorblendstatecreateflags, VkPipelineColorBlendStateCreateInfo *vkpipelinecolorblendstatecreateinfo_p);

#endif