#ifndef NALI_VK_PIPELINEVERTEXINPUTSTATECREATEINFO_H
#define NALI_VK_PIPELINEVERTEXINPUTSTATECREATEINFO_H

void vk_setPipelineVertexInputStateCreateInfo(VkPipelineVertexInputStateCreateFlags vkpipelinevertexinputstatecreateflags, VkVertexInputBindingDescription *vkvertexinputbindingdescription_p, VkVertexInputAttributeDescription *vkvertexinputattributedescription_p, uint8_t vkvertexinputattributedescription_size, VkPipelineVertexInputStateCreateInfo *vkpipelinevertexinputstatecreateinfo_p);

#endif