#!/bin/bash
F=CMakeLists.txt
sed -i '/set(ST linux)/c\#set(ST linux)' $F
sed -i '/  set(WL 1)/c\#  set(WL 1)' $F
sed -i '/  set(X11 1)/c\#  set(X11 1)' $F
sed -i '/  set(DRM 1)/c\#  set(DRM 1)' $F
sed -i '/set(ST android)/c\#set(ST android)' $F
sed -i '/set(ST win11)/c\#set(ST win11)' $F
sed -i '/set(ST mc)/c\#set(ST mc)' $F
sed -i '/set(GEN 1)/c\#set(GEN 1)' $F
sed -i '/set(CLIENT 1)/c\#set(CLIENT 1)' $F
sed -i '/set(SERVER 1)/c\#set(SERVER 1)' $F
sed -i '/set(VK 1)/c\#set(VK 1)' $F
sed -i '/  set(VK_DEBUG 1)/c\#  set(VK_DEBUG 1)' $F
sed -i '/set(GL 1)/c\#set(GL 1)' $F
sed -i '/set(TEST 1)/c\#set(TEST 1)' $F
sed -i '/set(TEST_3D 1)/c\#set(TEST_3D 1)' $F
sed -i '/set(DEBUG 1)/c\#set(DEBUG 1)' $F
