#!/bin/bash
F=CMakeLists.txt
sed -i '/#set(ST mc)/c\set(ST mc)' $F
sed -i '/set(CLIENT 1)/c\#set(CLIENT 1)' $F
sed -i '/set(SERVER 1)/c\#set(SERVER 1)' $F
sed -i '/#set(GL 1)/c\set(GL 1)' $F
sed -i '/set(DEBUG 1)/c\#set(DEBUG 1)' $F
