#!/bin/bash
F=CMakeLists.txt
sed -i '/#set(ST linux)/c\set(ST linux)' $F

while true; do
	echo '1)DRM'
	echo '2)WL'
	#echo '3)X11'
	read i
	if [ $i = 1 ]; then
		sed -i '/#set(DRM 1)/c\set(DRM 1)' $F
		sed -i '/#set(LIBINPUT 1)/c\set(LIBINPUT 1)' $F
		break
	elif [ $i = 2 ]; then
		sed -i '/#set(WL 1)/c\set(WL 1)' $F
		sed -i '/#set(WLINPUT 1)/c\set(WLINPUT 1)' $F
		break
	fi
done

#sed -i '/#set(CLIENT 1)/c\set(CLIENT 1)' $F
#sed -i '/#set(SERVER 1)/c\set(SERVER 1)' $F

#sed -i '/#set(FFMPEG 1)/c\set(FFMPEG 1)' $F

while true; do
	echo '1)RAW'
	echo '2)UDP'
	#echo '3)TCP'
	read i
	if [ $i = 1 ]; then
		sed -i '/#set(RAW 1)/c\set(RAW 1)' $F
		break
	elif [ $i = 2 ]; then
		sed -i '/#set(UDP 1)/c\set(UDP 1)' $F
		break
	fi
done

while true; do
	echo '1)CLIENT'
	echo '2)NONE'
	read i
	if [ $i = 1 ]; then
		sed -i '/#set(CLIENT 1)/c\set(CLIENT 1)' $F
		break
	elif [ $i = 2 ]; then
		break
	fi
done

while true; do
	echo '1)SERVER'
	echo '2)NONE'
	read i
	if [ $i = 1 ]; then
		sed -i '/#set(SERVER 1)/c\set(SERVER 1)' $F
		break
	elif [ $i = 2 ]; then
		break
	fi
done

#sed -i '/#set(PIPEWIRE 1)/c\set(PIPEWIRE 1)' $F

sed -i '/#set(VK 1)/c\set(VK 1)' $F
while true; do
	echo '1)VK_DEBUG'
	echo '2)NONE'
	read i
	if [ $i = 1 ]; then
		sed -i '/#  set(VK_DEBUG 1)/c\  set(VK_DEBUG 1)' $F
		break
	elif [ $i = 2 ]; then
		break
	fi
done

sed -i '/#set(DEBUG 1)/c\set(DEBUG 1)' $F
