#!/bin/bash
emerge -qa \
	sys-kernel/vanilla-sources sys-kernel/linux-firmware \
	sys-firmware/nvidia-firmware \
	sys-devel/gcc dev-debug/gdb \
	media-libs/vulkan-layers \
	gui-wm/hyprland x11-terms/kitty \
	app-editors/vim app-misc/screen \
	dev-util/android-sdk-build-tools dev-util/android-tools app-arch/zip app-arch/unzip \
	net-wireless/iwd net-wireless/bluez net-vpn/wireguard-tools
