#!/bin/bash
cd ..
mkdir -p prism/mcp
cd prism
wget https://github.com/PrismLauncher/PrismLauncher/releases/download/9.4/PrismLauncher-Linux-x86_64.AppImage
wget https://github.com/CleanroomMC/Cleanroom/releases/download/0.3.13-alpha/Cleanroom-MMC-instance-0.3.13-alpha.zip
chmod +x PrismLauncher-Linux-x86_64.AppImage
cd mcp
wget https://github.com/ModCoderPack/MCPMappingsArchive/raw/master/mcp_stable/39-1.12/mcp_stable-39-1.12.zip
unzip mcp_stable-39-1.12.zip
rm mcp_stable-39-1.12.zip
cd ../../SmallPointer
