#ifndef NALI_VK_GRAPHICSPIPELINE_MULTISAMPLESTATECREATEINFO_H
#define NALI_VK_GRAPHICSPIPELINE_MULTISAMPLESTATECREATEINFO_H

void vk_setPipelineMultisampleStateCreateInfo(VkPipelineMultisampleStateCreateFlags vkpipelinemultisamplestatecreateflags, VkPipelineMultisampleStateCreateInfo *vkpipelinemultisamplestatecreateinfo_p);

#endif