#ifndef NALI_VK_GRAPHICSPIPELINE_INPUTASSEMBLYSTATECREATEINFO_H
#define NALI_VK_GRAPHICSPIPELINE_INPUTASSEMBLYSTATECREATEINFO_H

void vk_setPipelineInputAssemblyStateCreateInfo(VkPipelineInputAssemblyStateCreateFlags vkpipelineinputassemblystatecreateflags, VkPipelineInputAssemblyStateCreateInfo *vkpipelineinputassemblystatecreateinfo_p);

#endif