#ifndef NALI_VK_GRAPHICSPIPELINE_VERTEXINPUTSTATECREATEINFO_H
#define NALI_VK_GRAPHICSPIPELINE_VERTEXINPUTSTATECREATEINFO_H

void vk_setPipelineVertexInputStateCreateInfo(VkVertexInputBindingDescription *vkvertexinputbindingdescription_p, VkVertexInputAttributeDescription *vkvertexinputattributedescription_p, uint8_t vkvertexinputattributedescription_size, VkPipelineVertexInputStateCreateInfo *vkpipelinevertexinputstatecreateinfo_p);

#endif