#ifndef NALI_VK_GRAPHICSPIPELINE_RASTERIZATIONSTATECREATEINFO_H
#define NALI_VK_GRAPHICSPIPELINE_RASTERIZATIONSTATECREATEINFO_H

void vk_setPipelineRasterizationStateCreateInfo(VkPipelineRasterizationStateCreateFlags vkpipelinerasterizationstatecreateflags, VkPipelineRasterizationStateCreateInfo *vkpipelinerasterizationstatecreateinfo_p);

#endif